### PR TITLE
Use maps for AST nodes

### PR DESCRIPTION
**Pull request by bruce**
To better support pattern matching (see #17).

A note on indentation: while, in general, I use the standard (hanging) indentation as done by the official elixir-lang/emacs-elixir project, for the [massive] introspection and kitchen sink AST trees I used the formatting as done by IEx, which is more condensed.

### CODE REVIEW

**Comment by joshprice** [comment]
Great work! Thanks for the PR.

I had started something similar but hadn't had time to finish it. Will be working on this over the weekend, so will compare approaches. I'll put together what I have in a PR so you can take a look at my solution.

One thing I got stuck on was figuring out an easy way to convert from Erlang Records to Elixir Structs, the manual way seemed straightforward but was surprised I couldn't find any baked in way to do it, perhaps you know a way?

**Comment by danielberkompas** [comment]
This looks good to me. Having the AST as maps definitely will help with pattern matching on the AST. @joshprice I didn't think Erlang records are required here, but I could be wrong? Were you thinking that the ast would be made up of structs rather than maps?

**Comment by joshprice** [comment]
Pushed up https://github.com/joshprice/graphql-elixir/pull/19 for discussion

**Comment by freshtonic** [comment]
Do we need to be concerned about the performance of Maps? According to José Valim (see his Elixir Conf keynote: https://youtu.be/9RB1JCKe3GY?t=1604), Maps are slow.

It may not be a big deal, because query execution is likely to be more time consuming than query parsing.

**Comment by joshprice** [comment]
Pretty happy with this as is, merging and will work on converting the maps to Elixir structs defined in #19

**Pull request merged**
