### PR TITLE
Stringify all the things!

### PR DESCRIPTION
**Pull request by peburrows**
Change all char lists to strings.

### CODE REVIEW

**Comment by peburrows** [comment]
Hrm, Travis CI failed. Looking into it now.

**Comment by joshprice** [comment]
Thanks for the PR! Looks like the specs are failing because of a couple of things:
1. I added a build matrix on Travis to check for compatibility across various versions (feedback on what might be appropriate here would be great - as I just guessed)
2. In order for the hex package to work out of the box I committed the generated `*.erl` files from the lexer and parser. This probably isn't a good idea as it may be generated with a different version of OTP than the user is on.

See https://github.com/philss/floki/pull/26 and https://github.com/philss/floki/issues/24

So the solution seems to be to not check in the generated lexer and parser files, but need to solve the problem of the hex package working correctly once installed.

**Comment by joshprice** [comment]
Added issues #12 and #11

**Comment by joshprice** [comment]
Have merged https://github.com/joshprice/graphql-elixir/pull/13 can you please rebase?

**Comment by joshprice** [comment]
Closing in favour of the rebased and passing #14

**Comment by peburrows** [comment]
Sorry, I didn't see your comments until just now. Looks like you sorted it all out :+1:

**Comment by joshprice** [comment]
No worrries, figured you were offline and was keen to see whether I'd solved the problem. All good!

**Pull request closed without merging**
