### PR TITLE
Allow reserved words as Names

### PR DESCRIPTION
**Pull request by joshprice**
`query`, `mutation`, etc are all now allowed as field names etc

Paired with @freshtonic

### CODE REVIEW

**Comment by joshprice** [comment]
Getting `shift/reduce` conflicts which need solving

**Comment by joshprice** [comment]
Shift/reduce issues resolved.

**Comment by freshtonic** [comment]
Great pairing session. Merge it :+1:

**Comment by joshprice** [comment]
Closes #6

**Comment by joshprice** [comment]
Closes #6

**Pull request merged**
